version: "2"
services:
  frontend:
    image: bayesimpact/react-base
    entrypoint: ""
    command: npm start
    ports:
      - 3002:80
    volumes:
      - ./src:/usr/app/src:ro
      # For linting.
      - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
      - ./.eslintignore:/usr/app/.eslintignore:ro
      # For releasing.
      - ./dist:/usr/app/dist:rw
    tty: true
  import:
    build: import
    volumes:
      - ./import/ttl_to_json.js:/work/ttl_to_json.js:ro
